<a href="https://colab.research.google.com/github/Mr-B-B/AI-ML/blob/main/NUMPY.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

                                        AIM:-Creating a 5x5 Identity Matrix

**Step 1: Import NumPy**

In [ ]:
import numpy as np

**Step 2: Create the Identity Matrix**

In [ ]:
identity_matrix = np.eye(5)

**Step 3: Print the Result**

In [ ]:
print("5x5 Identity Matrix:\n", identity_matrix)

5x5 Identity Matrix:
 [[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]
